"""First-run setup: udev rule, WirePlumber rule, audio service."""

import os
import json
import tempfile
import subprocess

from . import mixes, paths, service
from .profiles import PROFILES

UDEV_RULES = tuple(
    'SUBSYSTEM=="usb", '
    f'ATTR{{idVendor}}=="{profile.vid:04x}", '
    f'ATTR{{idProduct}}=="{profile.pid:04x}", MODE="0666"'
    for profile in PROFILES
)
UDEV_PRODUCT_IDS = tuple(f"{profile.pid:04x}" for profile in PROFILES)
UDEV_PATH = "/etc/udev/rules.d/99-openwave.rules"
UDEV_PATH_OLD = "/etc/udev/rules.d/99-wavexlr.rules"

CONFIG_ROOT = os.environ.get("XDG_CONFIG_HOME", os.path.expanduser("~/.config"))
WIREPLUMBER_NAME = "51-openwave-wave-xlr.conf"
WIREPLUMBER_PATH = os.path.join(CONFIG_ROOT, "wireplumber", "wireplumber.conf.d", WIREPLUMBER_NAME)

MIXES_NAME = "52-openwave-mixes.conf"
MIXES_PATH = os.path.join(CONFIG_ROOT, "pipewire", "pipewire.conf.d", MIXES_NAME)


SANDBOX_GUIDANCE = (
    "Native USB permissions and the capture service must be configured on the host "
    "using a native OpenWave install. The Flatpak panel cannot install or remove them."
)


def is_sandboxed():
    return bool(os.environ.get("FLATPAK_ID")) or os.path.exists("/.flatpak-info")


def _require_native():
    if is_sandboxed():
        raise RuntimeError(SANDBOX_GUIDANCE)


def wireplumber_source():
    return paths.data_file("wireplumber", WIREPLUMBER_NAME)


def mixes_source():
    return paths.data_file("pipewire", MIXES_NAME)


def udev_installed():
    for path in (UDEV_PATH, UDEV_PATH_OLD):
        try:
            with open(path) as f:
                content = f.read()
            if all(product_id in content for product_id in UDEV_PRODUCT_IDS):
                return True
        except (FileNotFoundError, PermissionError):
            continue
    return False


def service_installed():
    return service.is_installed()


def service_needs_refresh():
    """Whether an installed service still starts this installation's daemon."""
    return service.needs_refresh()


def wireplumber_installed():
    try:
        with open(WIREPLUMBER_PATH) as f:
            installed = f.read()
    except OSError:
        return False
    src = wireplumber_source()
    if src is None:
        return True
    try:
        with open(src) as f:
            return f.read() == installed
    except OSError:
        return True


def mixes_installed():
    return os.path.exists(MIXES_PATH)


def needs_setup():
    return (
        not udev_installed()
        or not service_installed()
        or service_needs_refresh()
        or not wireplumber_installed()
        or not mixes_installed()
    )


def install_udev():
    """Install udev rules via pkexec."""
    _require_native()
    rules = "\n".join(UDEV_RULES)
    trigger_lines = "\n".join(
        "udevadm trigger --subsystem-match=usb "
        f"--attr-match=idVendor={profile.vid:04x} "
        f"--attr-match=idProduct={profile.pid:04x}"
        for profile in PROFILES
    )
    script = f"""#!/bin/sh
cat > {UDEV_PATH} <<'EOF'
{rules}
EOF
udevadm control --reload-rules
{trigger_lines}
"""
    tmp = "/tmp/openwave-udev-setup.sh"
    with open(tmp, "w") as f:
        f.write(script)
    os.chmod(tmp, 0o755)

    r = subprocess.run(["pkexec", tmp], capture_output=True, text=True)
    os.unlink(tmp)
    return r.returncode == 0


def install_service():
    """Install and enable the audio service via the active backend."""
    _require_native()
    service.install()
    return True


def install_wireplumber():
    """Drop the suspend-disable rule into the user's WirePlumber config."""
    _require_native()
    src = wireplumber_source()
    if src is None:
        raise FileNotFoundError(
            f"WirePlumber rule source not found: share/openwave/wireplumber/"
            f"{WIREPLUMBER_NAME} is missing from this install"
        )
    with open(src) as f:
        content = f.read()
    os.makedirs(os.path.dirname(WIREPLUMBER_PATH), exist_ok=True)
    with open(WIREPLUMBER_PATH, "w") as f:
        f.write(content)
    return True


def render_mixes_conf(records):
    """Render validated definitions using JSON-escaped SPA string values."""
    entries = []
    for mix in mixes.normalize(records).values():
        values = {
            "factory.name": "support.null-audio-sink",
            "node.name": mix["sink"],
            "media.name": mix["sink"],
            "node.description": mix["description"],
            "media.class": "Audio/Sink",
            "audio.position": ["FL", "FR"],
            "object.linger": True,
            "monitor.channel-volumes": True,
            "state.restore-props": False,
            "priority.session": 0,
        }
        props = "\n".join(f"            {key} = {json.dumps(value, ensure_ascii=True)}" for key, value in values.items())
        entries.append("    { factory = adapter\n        args = {\n" + props + "\n        }\n    }\n")
    return "# GENERATED by OpenWave from mixdefs.json; edit mixes in the app.\ncontext.objects = [\n" + "".join(entries) + "]\n"


def install_mixes(records=None, *, path=None):
    """Atomically persist definitions for the next server start.

    Live graph creation is exclusively the Mixer worker's responsibility.
    A corrupt definition store raises without replacing the installed config.
    """
    content = render_mixes_conf(mixes.load_seeded() if records is None else records)
    target = path or MIXES_PATH
    directory = os.path.dirname(target) or "."
    os.makedirs(directory, exist_ok=True)
    fd, temporary = tempfile.mkstemp(prefix=".openwave-mixes-", dir=directory, text=True)
    try:
        with os.fdopen(fd, "w") as f:
            f.write(content)
        os.replace(temporary, target)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)
    return True


def run_setup():
    """Run full first-time setup. Returns (success, message)."""
    if is_sandboxed():
        return False, SANDBOX_GUIDANCE
    messages = []

    if not udev_installed():
        if install_udev():
            messages.append("USB permissions configured")
        else:
            return False, "Failed to set up USB permissions (pkexec cancelled?)"

    # Install the WirePlumber rule before starting the service so the daemon's
    # pw-cat attaches to a node that already has suspend disabled.
    if not wireplumber_installed():
        try:
            install_wireplumber()
            messages.append(
                "WirePlumber rule installed (restart wireplumber to apply)"
            )
        except Exception as e:
            return False, f"Failed to install WirePlumber rule: {e}"

    if not mixes_installed():
        try:
            install_mixes()
            messages.append(
                "Mix sinks installed (restart PipeWire to apply)"
            )
        except Exception as e:
            return False, f"Failed to install mix sinks: {e}"

    if not service_installed():
        try:
            install_service()
            messages.append("Audio service installed and started")
        except Exception as e:
            return False, f"Failed to install service: {e}"
    elif service_needs_refresh():
        try:
            install_service()
            messages.append("Audio service updated for this install")
        except Exception as e:
            return False, f"Failed to update service: {e}"

    return True, ". ".join(messages) if messages else "Already configured"
