use crate::{
    paths::{self, RuntimePaths},
    service::{self, HostCommands, HostContext},
};
use openwave_core::{
    model::{ErrorCode, Mix, Mixes, OperationError, Result, default_mixes, normalize_mixes},
    profiles::PROFILES,
};
use sha2::{Digest, Sha256};
use std::{
    collections::BTreeMap,
    fs::{self, File},
    io::{Read, Write},
    os::unix::fs::MetadataExt,
    path::{Path, PathBuf},
    time::Duration,
};

pub const SANDBOX_GUIDANCE: &str = "Native USB permissions and the capture service must be configured on the host using a native OpenWave install. The Flatpak panel cannot install or remove them.";
pub const WIREPLUMBER_NAME: &str = "51-openwave-wave-xlr.conf";
pub const MIXES_NAME: &str = "52-openwave-mixes.conf";
const RULE_NAME: &str = "99-openwave.rules";
const OLD_RULE_NAME: &str = "99-wavexlr.rules";
const RULE_DIRECTORY: &str = "/etc/udev/rules.d";
#[derive(Debug, Clone)]
pub struct SetupState {
    pub required: bool,
    pub message: String,
}
#[derive(Debug, Clone)]
pub struct SetupOutcome {
    pub needs_replug: bool,
    pub message: String,
}
pub fn is_sandboxed() -> bool {
    std::env::var_os("FLATPAK_ID").is_some_and(|s| !s.is_empty())
        || Path::new("/.flatpak-info").exists()
}
pub fn udev_rules() -> String {
    PROFILES.iter().map(|p| format!("SUBSYSTEM==\"usb\", ATTR{{idVendor}}==\"{:04x}\", ATTR{{idProduct}}==\"{:04x}\", MODE=\"0666\"\n",p.vid,p.pid)).collect()
}
/// Parse the complete rule meaning. Comments, disabled PIDs and incidental text
/// never count as permissions; additional selectors/actions are not our rule.
fn parse_rule(line: &str) -> Option<(u16, u16)> {
    let line = line.trim();
    if line.is_empty() || line.starts_with('#') {
        return None;
    }
    let mut fields = BTreeMap::new();
    for expression in line.split(',') {
        let expression = expression.trim();
        let (left, value, equality) = if let Some((left, value)) = expression.split_once("==") {
            (left, value, true)
        } else {
            let (left, value) = expression.split_once('=')?;
            (left, value, false)
        };
        let left = left.trim();
        let value = value.trim().strip_prefix('"')?.strip_suffix('"')?;
        if value.contains('"') || fields.insert(left, (value, equality)).is_some() {
            return None;
        }
    }
    if fields.len() != 4
        || fields.get("SUBSYSTEM") != Some(&("usb", true))
        || fields.get("MODE") != Some(&("0666", false))
    {
        return None;
    }
    let (vid, veq) = fields.get("ATTR{idVendor}")?;
    let (pid, peq) = fields.get("ATTR{idProduct}")?;
    if !veq || !peq || vid.len() != 4 || pid.len() != 4 {
        return None;
    }
    Some((
        u16::from_str_radix(vid, 16).ok()?,
        u16::from_str_radix(pid, 16).ok()?,
    ))
}
pub fn udev_contents_cover(text: &str) -> bool {
    let pairs: Vec<_> = text.lines().filter_map(parse_rule).collect();
    PROFILES.iter().all(|p| pairs.contains(&(p.vid, p.pid)))
}
fn owned_rule_file(text: &str) -> bool {
    let mut count = 0;
    for line in text
        .lines()
        .map(str::trim)
        .filter(|s| !s.is_empty() && !s.starts_with('#'))
    {
        let Some((vid, pid)) = parse_rule(line) else {
            return false;
        };
        if !PROFILES.iter().any(|p| p.vid == vid && p.pid == pid) {
            return false;
        }
        count += 1;
    }
    count > 0
}
fn udev_installed(host: &HostContext) -> Result<bool> {
    for name in [RULE_NAME, OLD_RULE_NAME] {
        if let Some(text) = service::read_optional(&host.udev_directory.join(name))? {
            if udev_contents_cover(&text) {
                return Ok(true);
            }
        }
    }
    Ok(false)
}
pub fn mix_definition_token(mix: &Mix) -> String {
    let bytes = serde_json::to_vec(&[mix.id.as_str(), mix.sink.as_str(), mix.description.as_str()])
        .expect("string array serialization");
    crate::installation::digest_hex(Sha256::digest(bytes))
}
pub fn render_mixes_conf(mixes: &Mixes) -> Result<String> {
    let checked = normalize_mixes(serde_json::to_value(mixes)?)?;
    let mut text = String::from(
        "# GENERATED by OpenWave from mixdefs.json; edit mixes in the app.\ncontext.objects = [\n",
    );
    for mix in checked.values() {
        let values = serde_json::json!({
            "factory.name":"support.null-audio-sink", "node.name":mix.sink, "media.name":mix.sink,
            "node.description":mix.description, "media.class":"Audio/Sink", "audio.position":["FL","FR"],
            "object.linger":true, "monitor.channel-volumes":true, "state.restore-props":false,
            "priority.session":0, "openwave.mix-id":mix.id.as_str(), "openwave.definition":mix_definition_token(mix)
        });
        text.push_str("    { factory = adapter\n        args = {\n");
        for (key, value) in values.as_object().expect("literal object") {
            text.push_str("            ");
            text.push_str(key);
            text.push_str(" = ");
            text.push_str(&serde_json::to_string(value)?);
            text.push('\n');
        }
        text.push_str("        }\n    }\n");
    }
    text.push_str("]\n");
    Ok(text)
}
fn stored_mixes(host: &HostContext) -> Result<Mixes> {
    let path = host.config_home.join("openwave/mixdefs.json");
    match service::read_optional(&path)? {
        None => Ok(default_mixes()),
        Some(text) => serde_json::from_str(&text)
            .map_err(OperationError::from)
            .and_then(normalize_mixes)
            .map_err(|e| {
                OperationError::new(
                    ErrorCode::CorruptStore,
                    format!("{}: {e}; file preserved", path.display()),
                )
            }),
    }
}
fn mixes_path(host: &HostContext) -> PathBuf {
    host.config_home
        .join("pipewire/pipewire.conf.d")
        .join(MIXES_NAME)
}
fn wireplumber_path(host: &HostContext) -> PathBuf {
    host.config_home
        .join("wireplumber/wireplumber.conf.d")
        .join(WIREPLUMBER_NAME)
}
pub fn write_mixes_conf_with(mixes: &Mixes, host: &HostContext) -> Result<()> {
    let content = render_mixes_conf(mixes)?;
    stored_mixes(host)?; // A caller cannot replace integration derived from a corrupt store.
    service::atomic_write(&mixes_path(host), &content)
}
pub fn write_mixes_conf(_paths: &RuntimePaths, mixes: &Mixes) -> Result<()> {
    write_mixes_conf_with(mixes, &HostContext::discover()?)
}
pub fn inspect_with(paths: &RuntimePaths, host: &HostContext) -> Result<SetupState> {
    let mixes = stored_mixes(host)?;
    if host.sandboxed {
        return Ok(SetupState {
            required: false,
            message: SANDBOX_GUIDANCE.into(),
        });
    }
    let source = fs::read_to_string(paths.data_file(&format!("wireplumber/{WIREPLUMBER_NAME}"))?)?;
    let service = service::status_with(paths, host)?;
    let needed = !udev_installed(host)?
        || service::read_optional(&wireplumber_path(host))?.as_deref() != Some(&source)
        || service::read_optional(&mixes_path(host))?.as_deref()
            != Some(&render_mixes_conf(&mixes)?)
        || !service.running
        || service.failed
        || service.message.contains("needs refresh");
    Ok(SetupState {
        required: needed,
        message: if needed {
            format!("Setup required. {}", service.message)
        } else {
            "Already configured".into()
        },
    })
}
pub fn inspect(paths: &RuntimePaths) -> Result<SetupState> {
    inspect_with(paths, &HostContext::discover()?)
}
pub fn run_with(paths: &RuntimePaths, mixes: &Mixes, host: &HostContext) -> Result<SetupOutcome> {
    host.require_native()?;
    // Validate all read-only prerequisites before changing the first host file.
    stored_mixes(host)?;
    let mix_text = render_mixes_conf(mixes)?;
    let wp_text = fs::read_to_string(paths.data_file(&format!("wireplumber/{WIREPLUMBER_NAME}"))?)?;
    let service_status = service::status_with(paths, host)?;
    let admin_service = !host.commands.available("systemctl");
    if admin_service && !service_status.running {
        return Err(OperationError::new(
            ErrorCode::Unsupported,
            "Have an administrator configure/start wavexlr-audio before native setup; OpenWave does not manufacture a privileged runit installation",
        ));
    }
    let mut messages = Vec::new();
    let mut needs_replug = false;
    if !udev_installed(host)? {
        paths::trusted_for_root(&paths.maintenance).map_err(|e| OperationError::new(ErrorCode::Identity,format!("Cannot elevate this maintenance helper: {e}. Ask an administrator to install OpenWave or its exact USB rules.")))?;
        host.command(
            "pkexec",
            &[service::text_path(&paths.maintenance)?, "install-udev"],
            Duration::from_secs(120),
        )?;
        messages.push("USB permissions configured; reconnect the device");
        needs_replug = true;
    }
    let wp_path = wireplumber_path(host);
    if service::read_optional(&wp_path)?.as_deref() != Some(&wp_text) {
        if host.commands.package_owner(&[wp_path.clone()])?.is_some() {
            return Err(OperationError::new(
                ErrorCode::Identity,
                "WirePlumber rule is package-owned; preserved",
            ));
        }
        service::atomic_write(&wp_path, &wp_text)?;
        messages.push("WirePlumber rule installed; takes effect at the next WirePlumber start");
    }
    if service::read_optional(&mixes_path(host))?.as_deref() != Some(&mix_text) {
        service::atomic_write(&mixes_path(host), &mix_text)?;
        messages.push("Mix sinks installed; takes effect at the next PipeWire start");
    }
    if !admin_service {
        service::install_with(paths, host)?;
    }
    messages.push(if admin_service {
        "Existing administrator capture service retained"
    } else {
        "Capture service configured"
    });
    Ok(SetupOutcome {
        needs_replug,
        message: messages.join(". "),
    })
}
pub fn run(paths: &RuntimePaths, mixes: &Mixes) -> Result<SetupOutcome> {
    run_with(paths, mixes, &HostContext::discover()?)
}

// Privileged maintenance entry points have fixed roots/names, never caller file lists.
// Directory descriptors stay pinned across reads, comparison and rename/unlink.
fn privileged_directory() -> Result<File> {
    use rustix::fs::{Mode, OFlags, open, openat};
    if !rustix::process::geteuid().is_root() {
        return Err(OperationError::new(
            ErrorCode::Unsupported,
            "This exact USB-rule operation requires administrator authorization",
        ));
    }
    if is_sandboxed() {
        return Err(OperationError::new(
            ErrorCode::Unsupported,
            SANDBOX_GUIDANCE,
        ));
    }
    let mut dir = File::from(
        open(
            "/",
            OFlags::RDONLY | OFlags::DIRECTORY | OFlags::CLOEXEC,
            Mode::empty(),
        )
        .map_err(std::io::Error::from)?,
    );
    for component in ["etc", "udev", "rules.d"] {
        let meta = dir.metadata()?;
        if meta.uid() != 0 || meta.mode() & 0o022 != 0 {
            return Err(OperationError::new(
                ErrorCode::Identity,
                "Untrusted USB rules ancestry",
            ));
        }
        dir = File::from(
            openat(
                &dir,
                component,
                OFlags::RDONLY | OFlags::DIRECTORY | OFlags::NOFOLLOW | OFlags::CLOEXEC,
                Mode::empty(),
            )
            .map_err(std::io::Error::from)?,
        );
    }
    let meta = dir.metadata()?;
    if meta.uid() != 0 || meta.mode() & 0o022 != 0 {
        return Err(OperationError::new(
            ErrorCode::Identity,
            "Untrusted USB rules directory",
        ));
    }
    Ok(dir)
}
struct RuleSnapshot {
    bytes: String,
    device: u64,
    inode: u64,
}
fn root_rule(dir: &File, name: &str) -> Result<Option<RuleSnapshot>> {
    use rustix::fs::{Mode, OFlags, openat};
    let fd = match openat(
        dir,
        name,
        OFlags::RDONLY | OFlags::NOFOLLOW | OFlags::CLOEXEC,
        Mode::empty(),
    ) {
        Ok(fd) => fd,
        Err(rustix::io::Errno::NOENT) => return Ok(None),
        Err(e) => return Err(std::io::Error::from(e).into()),
    };
    let file = File::from(fd);
    let meta = file.metadata()?;
    if !meta.is_file()
        || meta.uid() != 0
        || meta.mode() & 0o022 != 0
        || meta.len() > 4 * 1024 * 1024
    {
        return Err(OperationError::new(
            ErrorCode::Identity,
            "Untrusted USB rule file; preserved",
        ));
    }
    let mut bytes = String::new();
    file.take(4 * 1024 * 1024 + 1).read_to_string(&mut bytes)?;
    if bytes.len() > 4 * 1024 * 1024 || !owned_rule_file(&bytes) {
        return Err(OperationError::new(
            ErrorCode::Identity,
            "USB rule has unowned content; preserved",
        ));
    }
    Ok(Some(RuleSnapshot {
        bytes,
        device: meta.dev(),
        inode: meta.ino(),
    }))
}
fn unchanged_rule(dir: &File, name: &str, accepted: Option<&RuleSnapshot>) -> Result<()> {
    let current = root_rule(dir, name)?;
    let same = match (accepted, current) {
        (None, None) => true,
        (Some(a), Some(b)) => a.device == b.device && a.inode == b.inode && a.bytes == b.bytes,
        _ => false,
    };
    if same {
        Ok(())
    } else {
        Err(OperationError::new(
            ErrorCode::Identity,
            "USB rule changed during operation; preserved",
        ))
    }
}
fn update_rules(commands: &dyn HostCommands) -> Result<()> {
    let binary =
        fs::canonicalize(service::find_program("udevadm").ok_or_else(|| {
            OperationError::new(ErrorCode::Unavailable, "udevadm is unavailable")
        })?)?;
    paths::trusted_for_root(&binary)?;
    let program = service::text_path(&binary)?;
    let args = ["control", "--reload-rules"].map(str::to_owned);
    let output = commands.run(program, &args, Duration::from_secs(5))?;
    if !output.status.success() {
        return Err(OperationError::new(
            ErrorCode::Unavailable,
            format!(
                "udevadm reload failed: {}{}",
                String::from_utf8_lossy(&output.stdout),
                String::from_utf8_lossy(&output.stderr)
            ),
        ));
    }
    for profile in PROFILES {
        let args = vec![
            "trigger".into(),
            "--subsystem-match=usb".into(),
            format!("--attr-match=idVendor={:04x}", profile.vid),
            format!("--attr-match=idProduct={:04x}", profile.pid),
        ];
        let output = commands.run(program, &args, Duration::from_secs(5))?;
        if !output.status.success() {
            return Err(OperationError::new(
                ErrorCode::Unavailable,
                format!(
                    "udevadm trigger for {:04x}:{:04x} failed: {}{}",
                    profile.vid,
                    profile.pid,
                    String::from_utf8_lossy(&output.stdout),
                    String::from_utf8_lossy(&output.stderr)
                ),
            ));
        }
    }
    Ok(())
}
pub fn install_udev() -> Result<()> {
    use rustix::fs::{AtFlags, Mode, OFlags, openat, renameat, unlinkat};
    let dir = privileged_directory()?;
    let path = Path::new(RULE_DIRECTORY).join(RULE_NAME);
    if crate::installation::package_owner(&[path])?.is_some() {
        return Err(OperationError::new(
            ErrorCode::Identity,
            "USB rules are package-owned; use their package manager",
        ));
    }
    let before = root_rule(&dir, RULE_NAME)?;
    let temporary = format!(".openwave-{}", uuid::Uuid::new_v4().simple());
    let fd = openat(
        &dir,
        temporary.as_str(),
        OFlags::WRONLY | OFlags::CREATE | OFlags::EXCL | OFlags::NOFOLLOW | OFlags::CLOEXEC,
        Mode::from_bits_truncate(0o644),
    )
    .map_err(std::io::Error::from)?;
    let result = (|| -> Result<()> {
        let mut file = File::from(fd);
        file.write_all(udev_rules().as_bytes())?;
        file.sync_all()?;
        unchanged_rule(&dir, RULE_NAME, before.as_ref())?;
        renameat(&dir, temporary.as_str(), &dir, RULE_NAME).map_err(std::io::Error::from)?;
        dir.sync_all()?;
        Ok(())
    })();
    if result.is_err() {
        let _ = unlinkat(&dir, temporary.as_str(), AtFlags::empty());
    }
    result?;
    update_rules(&service::NativeCommands)
}
pub fn remove_udev() -> Result<()> {
    use rustix::fs::{AtFlags, unlinkat};
    let dir = privileged_directory()?;
    // Validate both files and manager boundaries before removing either one.
    let mut accepted = Vec::new();
    for name in [RULE_NAME, OLD_RULE_NAME] {
        let file = root_rule(&dir, name)?;
        if let Some(file) = file {
            if crate::installation::package_owner(&[Path::new(RULE_DIRECTORY).join(name)])?
                .is_none()
            {
                accepted.push((name, file));
            }
        }
    }
    if accepted.is_empty() {
        return Ok(());
    }
    for (name, file) in accepted {
        unchanged_rule(&dir, name, Some(&file))?;
        unlinkat(&dir, name, AtFlags::empty()).map_err(std::io::Error::from)?;
    }
    dir.sync_all()?;
    update_rules(&service::NativeCommands)
}
